source 'https://rubygems.org'

gem 'celluloid'
gem 'celluloid-io'
gem 'http'
gem 'reel'
gem 'bunny'
gem 'pry'
gem 'pry-nav'
gem 'neo4j'
gem 'selenium-webdriver'
gem 'rake'
gem 'listen'
gem 'awesome_print'